import { existsSync, mkdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import { transit_realtime } from 'gtfs-realtime-bindings';

import { decodeFeedMessage } from '../../src/domain/gtfsrt/decode-feed';
import { invariant } from '../../src/lib/invariant';

/**
 * Generates the synthetic Miami GTFS-realtime fixtures under `src/domain/gtfsrt/__fixtures__/`:
 *   - `vehicle-positions.fixture.ts` — four in-scope vehicles, for the decoder tests and the
 *     on-device decode probe (M1.13 / M1.16);
 *   - `live-feeds.fixture.ts` — the realtime mapper's cases (M4.2): the same four vehicles plus
 *     vehicles with no trip_id (one per branch, one on each shared trunk), a trip the schedule does
 *     not know, out-of-scope routes and a vehicle with no position; and a Swiftly-style TripUpdates
 *     feed (predictions, a canceled trip, a delay-only stop, a skipped stop, unusable updates).
 * Each feed is ENCODED by the reference GTFS-realtime bindings (the test oracle; Mac-side only, never
 * shipped), DECODED by our own decoder, and written as the bytes plus that decoded value;
 * oracle.test.ts then proves the reference decoder reads the same bytes identically.
 *
 * Deterministic by construction: fixed timestamps, no clock, no time zone, no randomness — so a
 * rerun reproduces both files byte for byte. Run from the repo root:
 *   npx tsx scripts/fixtures/make-gtfsrt-fixture.ts
 */

const FIXTURE_DIR = 'src/domain/gtfsrt/__fixtures__';
/** 2026-10-01T16:30:00Z, written as a number so no Date (and no time zone) is ever involved. */
const FEED_TIMESTAMP = 1_790_872_200;
const BYTES_PER_LINE = 16;
const GENERATED_BANNER = '// GENERATED by scripts/fixtures/make-gtfsrt-fixture.ts — do not edit by hand; rerun the generator.';

type VehicleSpec = {
  readonly id: string;
  readonly label: string;
  /** null: the vehicle reports its route but no trip. */
  readonly tripId: string | null;
  readonly routeId: string;
  readonly directionId: number;
  /** null: the vehicle reports no position at all. */
  readonly at: readonly [latitude: number, longitude: number] | null;
  readonly bearing: number;
  readonly speed: number;
  /** null: the vehicle carries no timestamp of its own (the feed header's applies). */
  readonly secondsOld: number | null;
  readonly stop?: { readonly stopId: string; readonly status: number; readonly sequence: number };
};

/**
 * Route ids 31009 (Metrorail), 14456 (Metromover Omni) and 14457 (Metromover Inner) and stop ids
 * 9512 / 9513 (Government Center rail, SB / NB) and 813 (Mover) are the ones the plan's §3 live
 * check named. Vehicle ids, trip ids and coordinates are synthetic. The last vehicle's label
 * carries a curly apostrophe so the fixture exercises multi-byte UTF-8.
 */
const VEHICLES: readonly VehicleSpec[] = [
  { id: 'rail-213', label: '213', tripId: 'fixture-rail-0815', routeId: '31009', directionId: 0, at: [25.7747, -80.1955], bearing: 0, speed: 0, secondsOld: 12, stop: { stopId: '9513', status: 1, sequence: 12 } },
  { id: 'rail-157', label: '157', tripId: 'fixture-rail-0822', routeId: '31009', directionId: 1, at: [25.7586, -80.1951], bearing: 182, speed: 15.6, secondsOld: 25, stop: { stopId: '9512', status: 2, sequence: 14 } },
  { id: 'mover-31', label: '31', tripId: 'fixture-omni-1630', routeId: '14456', directionId: 0, at: [25.7761, -80.1902], bearing: 270, speed: 6.7, secondsOld: 8, stop: { stopId: '813', status: 0, sequence: 3 } },
  { id: 'mover-07', label: 'Gov’t Center', tripId: 'fixture-inner-1631', routeId: '14457', directionId: 0, at: [25.7739, -80.1917], bearing: 45, speed: 4.2, secondsOld: 40 },
];

/**
 * The mapper's extra vehicles (M4.2). Positions are midpoints between two real stations
 * (src/domain/network/__fixtures__/real-stops.ts), rounded to 4 decimals (≈ 10 m).
 */
const MAPPER_VEHICLES: readonly VehicleSpec[] = [
  ...VEHICLES,
  // Metrorail with no trip_id: Green branch (Okeechobee–Hialeah), Airport branch (MIA–Earlington
  // Heights), the shared trunk (Brickell–Vizcaya; no timestamp of its own, so the header's applies).
  { id: 'rail-301', label: '301', tripId: null, routeId: '31009', directionId: 0, at: [25.8405, -80.2903], bearing: 90, speed: 17.2, secondsOld: 15 },
  { id: 'rail-302', label: '302', tripId: null, routeId: '31009', directionId: 1, at: [25.8052, -80.2443], bearing: 300, speed: 14.1, secondsOld: 20 },
  { id: 'rail-303', label: '303', tripId: null, routeId: '31009', directionId: 0, at: [25.7568, -80.2037], bearing: 225, speed: 18.9, secondsOld: null },
  // A trip the schedule does not know (falsifier R8), on the Green branch (Northside–M.L. King).
  { id: 'rail-304', label: '304', tripId: 'fixture-rail-unknown', routeId: '31009', directionId: 0, at: [25.8391, -80.245], bearing: 160, speed: 12, secondsOld: 30 },
  // Omni/Brickell with no trip_id: on the shared track (College North–Wilkie D. Ferguson) and on the
  // Brickell-only loop (Financial District–Brickell).
  { id: 'mover-12', label: '12', tripId: null, routeId: '14456', directionId: 0, at: [25.7789, -80.1937], bearing: 270, speed: 5.5, secondsOld: 10 },
  { id: 'mover-19', label: '19', tripId: null, routeId: '14456', directionId: 1, at: [25.7615, -80.1941], bearing: 315, speed: 5.1, secondsOld: 10 },
  // Out of scope: the MIA airport Mover (14458, excluded by the plan) and a bus.
  { id: 'mia-mover-2', label: 'MIA 2', tripId: 'fixture-mia-1630', routeId: '14458', directionId: 0, at: [25.7965, -80.26], bearing: 0, speed: 8, secondsOld: 5 },
  { id: 'bus-1104', label: '1104', tripId: 'fixture-bus-1630', routeId: 'fixture-bus', directionId: 0, at: [25.7801, -80.2101], bearing: 90, speed: 9, secondsOld: 5 },
  // Reports a trip but no position: nothing to draw.
  { id: 'rail-305', label: '305', tripId: 'fixture-rail-0840', routeId: '31009', directionId: 0, at: null, bearing: 0, speed: 0, secondsOld: 5 },
];

type StopUpdateSpec = {
  readonly stopId: string | null;
  readonly sequence: number;
  /** Seconds after the feed timestamp the train departs (an absolute departure.time), or absent. */
  readonly inS?: number;
  readonly delay?: number;
  readonly relationship?: number;
};

type TripUpdateSpec = {
  readonly id: string;
  readonly tripId: string;
  readonly routeId: string;
  readonly directionId: number;
  readonly relationship: number;
  readonly stops: readonly StopUpdateSpec[];
};

const { SCHEDULED: TRIP_SCHEDULED, CANCELED: TRIP_CANCELED } = transit_realtime.TripDescriptor.ScheduleRelationship;
const { SKIPPED, NO_DATA } = transit_realtime.TripUpdate.StopTimeUpdate.ScheduleRelationship;

/** A Swiftly-style TripUpdates feed. Trip ids match MAPPER_VEHICLES; 9515 / 9513 are Brickell / Government Center NB. */
const TRIP_UPDATES: readonly TripUpdateSpec[] = [
  { id: 'tu-rail-0822', tripId: 'fixture-rail-0822', routeId: '31009', directionId: 1, relationship: TRIP_SCHEDULED, stops: [{ stopId: '9515', sequence: 8, inS: 300, delay: 120 }, { stopId: '9513', sequence: 9, inS: 420, delay: 120 }] },
  { id: 'tu-rail-0830', tripId: 'fixture-rail-0830', routeId: '31009', directionId: 0, relationship: TRIP_CANCELED, stops: [] },
  { id: 'tu-omni-1630', tripId: 'fixture-omni-1630', routeId: '14456', directionId: 0, relationship: TRIP_SCHEDULED, stops: [{ stopId: '813', sequence: 1, delay: 45 }, { stopId: '815', sequence: 2, relationship: SKIPPED }] },
  // Unusable updates: NO_DATA, a stop outside the schedule, and a stop given by sequence alone.
  { id: 'tu-rail-0845', tripId: 'fixture-rail-0845', routeId: '31009', directionId: 1, relationship: TRIP_SCHEDULED, stops: [{ stopId: '9513', sequence: 9, relationship: NO_DATA }, { stopId: '9999', sequence: 10, inS: 600 }, { stopId: null, sequence: 11, inS: 660 }] },
  { id: 'tu-bus-1630', tripId: 'fixture-bus-1630', routeId: 'fixture-bus', directionId: 0, relationship: TRIP_SCHEDULED, stops: [{ stopId: '1104', sequence: 4, inS: 120 }] },
];

function vehicleEntity(spec: VehicleSpec): transit_realtime.IFeedEntity {
  invariant(spec.secondsOld === null || (spec.secondsOld >= 0 && spec.secondsOld < 300), 'fixture vehicles are a few seconds to minutes old');
  invariant(spec.at === null || (spec.at[0] > 25 && spec.at[0] < 26.5 && spec.at[1] > -81 && spec.at[1] < -80), 'fixture vehicles are in Miami');
  const stop = spec.stop === undefined ? {} : { stopId: spec.stop.stopId, currentStatus: spec.stop.status, currentStopSequence: spec.stop.sequence };
  const trip = spec.tripId === null ? {} : { tripId: spec.tripId };
  const position = spec.at === null ? {} : { position: { latitude: spec.at[0], longitude: spec.at[1], bearing: spec.bearing, speed: spec.speed } };
  const timestamp = spec.secondsOld === null ? {} : { timestamp: FEED_TIMESTAMP - spec.secondsOld };
  return {
    id: `vehicle-${spec.id}`,
    vehicle: {
      trip: { ...trip, routeId: spec.routeId, directionId: spec.directionId, startDate: '20261001' },
      vehicle: { id: spec.id, label: spec.label },
      ...position,
      ...timestamp,
      ...stop,
    },
  };
}

function stopTimeUpdateOf(spec: StopUpdateSpec): transit_realtime.TripUpdate.IStopTimeUpdate {
  invariant(spec.sequence >= 0, 'a stop update has a stop sequence');
  invariant(spec.inS === undefined || spec.inS > 0, 'a predicted departure lies after the feed timestamp');
  const time = spec.inS === undefined ? {} : { time: FEED_TIMESTAMP + spec.inS };
  const delay = spec.delay === undefined ? {} : { delay: spec.delay };
  return {
    stopSequence: spec.sequence,
    ...(spec.stopId === null ? {} : { stopId: spec.stopId }),
    ...(spec.inS === undefined && spec.delay === undefined ? {} : { departure: { ...time, ...delay } }),
    ...(spec.relationship === undefined ? {} : { scheduleRelationship: spec.relationship }),
  };
}

function tripUpdateEntity(spec: TripUpdateSpec): transit_realtime.IFeedEntity {
  invariant(spec.relationship === TRIP_CANCELED || spec.stops.length > 0, 'only a canceled trip lists no stops');
  invariant(spec.stops.every((s, i) => i === 0 || s.sequence > (spec.stops[i - 1]?.sequence ?? 0)), 'stop updates come in stop order');
  const stopTimeUpdate = spec.stops.map((stop) => stopTimeUpdateOf(stop));
  return {
    id: spec.id,
    tripUpdate: {
      trip: { tripId: spec.tripId, routeId: spec.routeId, directionId: spec.directionId, startDate: '20261001', scheduleRelationship: spec.relationship },
      stopTimeUpdate,
      timestamp: FEED_TIMESTAMP,
    },
  };
}

/** The feed encoded by the reference bindings, as a plain Uint8Array (not a Node Buffer). */
function encodeFeed(entity: transit_realtime.IFeedEntity[]): Uint8Array {
  invariant(entity.length > 0, 'a fixture feed has entities');
  const plain: transit_realtime.IFeedMessage = {
    header: { gtfsRealtimeVersion: '2.0', incrementality: 0, timestamp: FEED_TIMESTAMP },
    entity,
  };
  const problem = transit_realtime.FeedMessage.verify(plain);
  invariant(problem === null, `the fixture feed is a valid FeedMessage: ${String(problem)}`);
  const bytes = Uint8Array.from(transit_realtime.FeedMessage.encode(transit_realtime.FeedMessage.fromObject(plain)).finish());
  invariant(bytes.length > 0, 'the encoded feed has bytes');
  return bytes;
}

function formatBytes(bytes: Uint8Array): string {
  invariant(bytes.length > 0, 'there are bytes to format');
  const lines: string[] = [];
  for (let at = 0; at < bytes.length; at += BYTES_PER_LINE) {
    const row = Array.from(bytes.subarray(at, at + BYTES_PER_LINE), (byte) => `0x${byte.toString(16).padStart(2, '0')},`);
    lines.push(`  ${row.join(' ')}`);
  }
  invariant(lines.length === Math.ceil(bytes.length / BYTES_PER_LINE), 'one line per 16 bytes');
  return lines.join('\n');
}

/** One generated feed: its export-name prefix and a one-line description (`{n}` = entities, `{bytes}` = size). */
type FeedOutput = { readonly name: string; readonly about: string; readonly entity: transit_realtime.IFeedEntity[] };

/** The bytes and decoded value of one feed, as two exports `<name>_BYTES` and `<name>_DECODED`. */
function renderFeed(feed: FeedOutput): string[] {
  const bytes = encodeFeed(feed.entity);
  const decoded = decodeFeedMessage(bytes);
  invariant(decoded.ok, `our decoder reads the ${feed.name} fixture: ${decoded.ok ? '' : decoded.error.message}`);
  invariant(decoded.value.entity.length === feed.entity.length, `every ${feed.name} entity decoded`);
  const about = feed.about.replace('{n}', String(feed.entity.length)).replace('{bytes}', String(bytes.length));
  return [
    `/** ${about} */`,
    `export const ${feed.name}_BYTES: Uint8Array = new Uint8Array([`,
    formatBytes(bytes),
    ']);',
    '',
    `/** What \`decodeFeedMessage(${feed.name}_BYTES)\` returns (oracle.test.ts proves the reference decoder agrees). */`,
    `export const ${feed.name}_DECODED: FeedMessage = ${JSON.stringify(decoded.value, null, 2)};`,
    '',
  ];
}

function renderFixture(feeds: readonly FeedOutput[]): string {
  invariant(feeds.length > 0, 'a fixture file holds at least one feed');
  const blocks = feeds.flatMap((feed) => renderFeed(feed));
  const text = [GENERATED_BANNER, "import type { FeedMessage } from '../types';", '', ...blocks].join('\n');
  invariant(!text.includes('\r'), 'the fixture uses LF line endings on every platform');
  return text;
}

function writeFixture(file: string, feeds: readonly FeedOutput[]): void {
  invariant(file.endsWith('.fixture.ts'), 'fixtures are named *.fixture.ts');
  const path = `${FIXTURE_DIR}/${file}`;
  const text = renderFixture(feeds);
  mkdirSync(dirname(join(process.cwd(), path)), { recursive: true });
  writeFileSync(path, text, 'utf8');
  invariant(statSync(path).size === Buffer.byteLength(text, 'utf8'), `${path} was written in full`);
  console.log(`wrote ${path} (${feeds.map((feed) => `${feed.name}: ${feed.entity.length} entities`).join(', ')})`);
}

function main(): number {
  invariant(existsSync('package.json') && existsSync('src/domain/gtfsrt'), 'run the generator from the repo root');
  invariant(MAPPER_VEHICLES.slice(0, VEHICLES.length).every((spec, i) => spec === VEHICLES[i]), 'the mapper feed starts with the probe vehicles');
  writeFixture('vehicle-positions.fixture.ts', [
    { name: 'VEHICLE_POSITIONS_FIXTURE', about: 'A synthetic Miami GTFS-realtime VehiclePositions feed: {n} vehicles, {bytes} bytes.', entity: VEHICLES.map(vehicleEntity) },
  ]);
  writeFixture('live-feeds.fixture.ts', [
    { name: 'LIVE_VEHICLES_FIXTURE', about: 'The realtime mapper’s VehiclePositions feed (M4.2): {n} vehicles, {bytes} bytes.', entity: MAPPER_VEHICLES.map(vehicleEntity) },
    { name: 'LIVE_TRIP_UPDATES_FIXTURE', about: 'The realtime mapper’s Swiftly-style TripUpdates feed (M4.2): {n} trips, {bytes} bytes.', entity: TRIP_UPDATES.map(tripUpdateEntity) },
  ]);
  return 0;
}

process.exitCode = main();
