import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

import { invariant } from '../../src/lib/invariant';
import { groupStopTimes, networkStops } from '../gtfs/build-network';
import { sha256Hex } from '../gtfs/idempotency';
import { loadFeed, type LoadedFeed } from '../gtfs/load-feed';
import { unzipFeed } from '../gtfs/unzip-feed';

/**
 * Generates the two REAL-feed fixtures the station and line tests run on, straight from the county
 * zip (public, keyless: scripts/gtfs/paths.ts FEED_URL), so no test touches the network and no
 * pattern is ever typed in by hand:
 *  - src/domain/network/__fixtures__/real-stops.ts — every in-scope stop: id, name, coordinates and
 *    the mode of the routes serving it;
 *  - src/domain/lines/__fixtures__/real-patterns.ts — every real pattern, i.e. distinct
 *    (route_id, ordered stop_ids, shape_id), with its trip count, direction and headsigns.
 * The feed's byte size and SHA-256 are written into both headers, so a fixture names the exact zip
 * it came from. Deterministic: the same zip regenerates both files byte for byte. From the repo root:
 *   npx tsx scripts/fixtures/make-network-fixtures.ts <path to google_transit.zip>
 */

const STOPS_OUTPUT = 'src/domain/network/__fixtures__/real-stops.ts';
const PATTERNS_OUTPUT = 'src/domain/lines/__fixtures__/real-patterns.ts';

type PatternRow = {
  routeId: string;
  shapeId: string;
  directionId: number;
  trips: number;
  headsigns: string[];
  stopIds: readonly string[];
};

/** Distinct (route, ordered stops, shape) over every loaded trip, sorted by route then shape then stops. */
function realPatterns(feed: LoadedFeed): PatternRow[] {
  const tripStops = groupStopTimes(feed);
  invariant(tripStops.ok, `the feed's trips each have stop times: ${tripStops.ok ? '' : tripStops.error.message}`);
  const rows = new Map<string, PatternRow>();
  for (const trip of feed.trips) {
    const stopIds = (tripStops.value.get(trip.trip_id) ?? []).map((row) => row.stop_id);
    const key = `${trip.route_id}|${trip.shape_id}|${stopIds.join(',')}`;
    const row = rows.get(key) ?? { routeId: trip.route_id, shapeId: trip.shape_id, directionId: trip.direction_id, trips: 0, headsigns: [], stopIds };
    invariant(row.directionId === trip.direction_id, `pattern ${key} runs in one direction`);
    row.trips += 1;
    row.headsigns = [...new Set([...row.headsigns, trip.trip_headsign])].sort();
    rows.set(key, row);
  }
  const sorted: PatternRow[] = [];
  for (const key of [...rows.keys()].sort()) {
    const row = rows.get(key);
    invariant(row !== undefined, `pattern ${key} is grouped`);
    sorted.push(row);
  }
  return sorted;
}

function header(zipBytes: Uint8Array, what: string): string[] {
  invariant(zipBytes.length > 0, 'the fixture comes from a real zip');
  const lines = [
    '// GENERATED by scripts/fixtures/make-network-fixtures.ts — do not edit by hand; rerun the generator.',
    `// Source: the county GTFS zip, ${zipBytes.length} bytes, sha256 ${sha256Hex(zipBytes)}.`,
    `// ${what}`,
  ];
  invariant(lines.every((line) => !line.includes('\n')), 'header lines are single lines');
  return lines;
}

function renderStops(zipBytes: Uint8Array, feed: LoadedFeed): string {
  const stops = networkStops(feed);
  invariant(stops.ok, `every stop is served by one mode: ${stops.ok ? '' : stops.error.message}`);
  const sorted = [...stops.value].sort((a, b) => Number(a.stopId) - Number(b.stopId) || (a.stopId < b.stopId ? -1 : 1));
  const rows = sorted.map(
    (s) => `  { stopId: ${JSON.stringify(s.stopId)}, name: ${JSON.stringify(s.name)}, latitude: ${s.latitude}, longitude: ${s.longitude}, mode: '${s.mode}' },`,
  );
  const text = [
    ...header(zipBytes, `Every in-scope stop (routes 31009, 14457, 14456): ${rows.length} stops, names exactly as published.`),
    "import type { StopInput } from '../stations';",
    '',
    'export const REAL_STOPS: readonly StopInput[] = [',
    ...rows,
    '];',
    '',
  ].join('\n');
  invariant(rows.length === feed.stops.length, 'every loaded stop is written');
  return text;
}

function renderPattern(p: PatternRow): string {
  invariant(p.trips > 0 && p.headsigns.length > 0, `pattern ${p.routeId}/${p.shapeId} has trips and headsigns`);
  invariant(p.stopIds.length >= 2, `pattern ${p.routeId}/${p.shapeId} visits at least two stops`);
  return [
    '  {',
    `    routeId: ${JSON.stringify(p.routeId)},`,
    `    shapeId: ${JSON.stringify(p.shapeId)},`,
    `    directionId: ${p.directionId},`,
    `    trips: ${p.trips},`,
    `    headsigns: ${JSON.stringify(p.headsigns)},`,
    `    stopIds: ${JSON.stringify(p.stopIds)},`,
    '  },',
  ].join('\n');
}

function renderPatterns(zipBytes: Uint8Array, feed: LoadedFeed): string {
  const patterns = realPatterns(feed);
  invariant(patterns.length > 0, 'the feed has patterns');
  const rows = patterns.map(renderPattern);
  const what = `Every real pattern — distinct (route_id, ordered stop_ids, shape_id): ${patterns.length} patterns.`;
  const text = [
    ...header(zipBytes, what),
    '',
    'export type RealPattern = {',
    '  readonly routeId: string;',
    '  readonly shapeId: string;',
    '  readonly directionId: number;',
    '  /** How many trips in the feed run this exact pattern. */',
    '  readonly trips: number;',
    '  readonly headsigns: readonly string[];',
    '  readonly stopIds: readonly string[];',
    '};',
    '',
    'export const REAL_PATTERNS: readonly RealPattern[] = [',
    ...rows,
    '];',
    '',
  ].join('\n');
  invariant(!text.includes('\r'), 'the fixture uses LF line endings');
  return text;
}

function main(): number {
  invariant(existsSync('package.json') && existsSync('src/domain/lines'), 'run the generator from the repo root');
  const zipPath = process.argv[2];
  invariant(zipPath !== undefined && existsSync(zipPath), 'pass the path of the county google_transit.zip');
  const zipBytes = new Uint8Array(readFileSync(zipPath));
  const files = unzipFeed(zipBytes);
  invariant(files.ok, `the zip unpacks: ${files.ok ? '' : files.error.message}`);
  const feed = loadFeed(files.value);
  invariant(feed.ok, `the feed loads: ${feed.ok ? '' : feed.error.message}`);
  for (const [path, text] of [
    [STOPS_OUTPUT, renderStops(zipBytes, feed.value)],
    [PATTERNS_OUTPUT, renderPatterns(zipBytes, feed.value)],
  ] as const) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, text, 'utf8');
    invariant(statSync(path).size === Buffer.byteLength(text, 'utf8'), `${path} was written in full`);
    console.log(`wrote ${path} (${Buffer.byteLength(text, 'utf8')} bytes)`);
  }
  return 0;
}

process.exitCode = main();
