import type { LineId } from '../../../src/domain/lines/line-catalog';
import { invariant } from '../../../src/lib/invariant';
import { isoAt } from './clock';
import type { DeparturesBuild } from './departures';
import type { FixtureDay } from './schedule-facts';
import type { VehicleFeed } from './vehicles';

/**
 * The two synthetic live fixture modules as TypeScript text. Each STARTS with the comment the
 * public-repo data rule asks for: it is synthetic, which script generates it, from what (the public
 * static GTFS), and why.
 */

export const FIXTURE_HEADER = [
  '// SYNTHETIC realtime fixture, GENERATED by scripts/fixtures/make-live-fixtures.ts: do not edit by hand.',
  '// Built from the public static GTFS alone (assets/db/schedule.db: real trip_ids, stops and shapes) with',
  '// synthetic positions, times and ids, in the field structure of the live Transitland responses.',
  '// Why: the public-repo data rule (plan §3). No real Transitland or Swiftly realtime content is ever',
  '// committed; real captures stay in the gitignored capture directory and are compared by structure only.',
].join('\n');

const BYTES_PER_LINE = 16;

function formatBytes(bytes: Uint8Array): string {
  invariant(bytes.length > 0, 'there are bytes to format');
  const lines: string[] = [];
  for (let at = 0; at < bytes.length; at += BYTES_PER_LINE) {
    const row = Array.from(bytes.subarray(at, at + BYTES_PER_LINE), (byte) => `0x${byte.toString(16).padStart(2, '0')},`);
    lines.push(`  ${row.join(' ')}`);
  }
  invariant(lines.length === Math.ceil(bytes.length / BYTES_PER_LINE), 'one line per 16 bytes');
  return lines.join('\n');
}

function formatTripLines(name: string, about: string, tripLines: readonly (readonly [string, LineId])[]): string[] {
  invariant(tripLines.length > 0, `${name} lists trips`);
  invariant(tripLines.every(([trip], i) => i === 0 || (tripLines[i - 1]?.[0] ?? '') < trip), 'trips are sorted and distinct');
  return [
    `/** ${about} */`,
    `export const ${name}: readonly (readonly [tripId: string, lineId: LineId])[] = [`,
    ...tripLines.map(([trip, line]) => `  ['${trip}', '${line}'],`),
    '];',
  ];
}

export function renderVehicleFixture(feed: VehicleFeed, day: FixtureDay, feedEpoch: number): string {
  const { rail, mover, bus, idle } = feed.counts;
  invariant(rail > 0 && mover > 0 && bus > 0, 'the feed has rail, Mover and out-of-scope vehicles');
  const text = [
    FIXTURE_HEADER,
    "import type { LineId } from '../../lines/line-catalog';",
    '',
    '/**',
    ` * A synthetic Miami-Dade VehiclePositions feed at ${isoAt(feedEpoch, day.offsetS)} (header timestamp ${feedEpoch}):`,
    ` * ${rail + mover + bus + idle} vehicles: ${rail} Metrorail and ${mover} Metromover on their scheduled trips, ON their shapes;`,
    ` * ${bus} buses on synthetic routes; ${idle} on no trip. ${feed.bytes.length} bytes.`,
    ' */',
    'export const SYNTHETIC_VEHICLE_POSITIONS_BYTES: Uint8Array = new Uint8Array([',
    formatBytes(feed.bytes),
    ']);',
    '',
    ...formatTripLines('SYNTHETIC_VEHICLE_TRIP_LINES', 'trip_id → line (schedule.db) of every rail and Mover vehicle above: the schedule facts a test network needs.', feed.tripLines),
    '',
  ].join('\n');
  invariant(!text.includes('\r'), 'LF line endings on every platform');
  return text;
}

export function renderDeparturesFixture(build: DeparturesBuild, day: FixtureDay, feedEpoch: number): string {
  const stops = Object.keys(build.responses);
  invariant(stops.join(',') === '9512,9513', 'one response per Government Center rail platform: 9512 SB, 9513 NB');
  const text = [
    FIXTURE_HEADER,
    "import type { LineId } from '../../lines/line-catalog';",
    '',
    '/**',
    ` * Synthetic Transitland departures responses (\`stops/<feed>:<stop_id>/departures?next=3600\`) for Government`,
    ` * Center rail, 9512 (southbound) and 9513 (northbound), asked at ${isoAt(feedEpoch, day.offsetS)}: real scheduled`,
    ' * trips; rows due within 40 min SCHEDULED with a synthetic estimate, later rows STATIC.',
    ' */',
    `export const SYNTHETIC_DEPARTURES = ${JSON.stringify(build.responses, null, 2)};`,
    '',
    ...formatTripLines('SYNTHETIC_DEPARTURE_TRIP_LINES', 'trip_id → line (schedule.db) of every departure row above: the schedule facts a test network needs.', build.tripLines),
    '',
  ].join('\n');
  invariant(!text.includes('\r'), 'LF line endings on every platform');
  return text;
}
