// GENERATED by scripts/fixtures/make-network-fixtures.ts — do not edit by hand; rerun the generator.
// Source: the county GTFS zip, 8419295 bytes, sha256 785460181e910e47af9172ccb9da0b10aa61ba9d55539fd6b69d0ad181758ef5.
// Every real pattern — distinct (route_id, ordered stop_ids, shape_id): 15 patterns.

export type RealPattern = {
  readonly routeId: string;
  readonly shapeId: string;
  readonly directionId: number;
  /** How many trips in the feed run this exact pattern. */
  readonly trips: number;
  readonly headsigns: readonly string[];
  readonly stopIds: readonly string[];
};

export const REAL_PATTERNS: readonly RealPattern[] = [
  {
    routeId: "14456",
    shapeId: "123745",
    directionId: 0,
    trips: 596,
    headsigns: ["DOWNTOWN"],
    stopIds: ["795","796","797","798","799","800","811","812","813"],
  },
  {
    routeId: "14456",
    shapeId: "123746",
    directionId: 0,
    trips: 597,
    headsigns: ["DOWNTOWN"],
    stopIds: ["801","802","803","804","805","806","807","808","809","810","811","812","813"],
  },
  {
    routeId: "14456",
    shapeId: "123747",
    directionId: 1,
    trips: 596,
    headsigns: ["SCHOOL BOARD"],
    stopIds: ["813","815","822","823","824","825","826","827","828","829","796","831"],
  },
  {
    routeId: "14456",
    shapeId: "123748",
    directionId: 1,
    trips: 595,
    headsigns: ["FINANCIAL DISTRICT"],
    stopIds: ["813","815","816","817","818","819","820","821"],
  },
  {
    routeId: "14457",
    shapeId: "123750",
    directionId: 0,
    trips: 940,
    headsigns: ["INNER LOOP"],
    stopIds: ["832","833","834","813"],
  },
  {
    routeId: "14457",
    shapeId: "123751",
    directionId: 1,
    trips: 937,
    headsigns: ["INNER LOOP"],
    stopIds: ["813","837","838","839","840","841"],
  },
  {
    routeId: "31009",
    shapeId: "211235",
    directionId: 0,
    trips: 171,
    headsigns: ["EARLINGTON HEIGHTS"],
    stopIds: ["10494","9500"],
  },
  {
    routeId: "31009",
    shapeId: "211236",
    directionId: 0,
    trips: 71,
    headsigns: ["ORANGE LINE DADELAND SOUTH"],
    stopIds: ["10494","9500","9502","9504","9506","9508","9510","9512","9514","9516","9518","9520","9522","9524","9526","9528"],
  },
  {
    routeId: "31009",
    shapeId: "211239",
    directionId: 0,
    trips: 73,
    headsigns: ["GREEN LINE DADELAND SOUTH"],
    stopIds: ["9486","9488","9490","9492","9494","9496","9498","9500","9502","9504","9506","9508","9510","9512","9514","9516","9518","9520","9522","9524","9526","9528"],
  },
  {
    routeId: "31009",
    shapeId: "211246",
    directionId: 0,
    trips: 118,
    headsigns: ["EHT - CUL SINGLE TRACK AFTER 8PM"],
    stopIds: ["9486","9488","9490","9492","9494","9496","9498","9500","9502","9504","9506","9508","9510","9512","9514","9516","9518","9520","9522","9524","9526","9528"],
  },
  {
    routeId: "31009",
    shapeId: "211250",
    directionId: 1,
    trips: 168,
    headsigns: ["ORANGE LINE AIRPORT STATION"],
    stopIds: ["9501","10495"],
  },
  {
    routeId: "31009",
    shapeId: "211251",
    directionId: 1,
    trips: 75,
    headsigns: ["ORANGE LINE AIRPORT STATION"],
    stopIds: ["9529","9527","9525","9523","9521","9519","9517","9515","9513","9511","9509","9507","9505","9503","9501","10495"],
  },
  {
    routeId: "31009",
    shapeId: "211260",
    directionId: 1,
    trips: 75,
    headsigns: ["GREEN LINE PALMETTO STATION"],
    stopIds: ["9529","9527","9525","9523","9521","9519","9517","9515","9513","9511","9509","9507","9505","9503","9501","9499","9497","9495","9493","9491","9489","9487"],
  },
  {
    routeId: "31009",
    shapeId: "211263",
    directionId: 1,
    trips: 118,
    headsigns: ["EHT - CUL SINGLE TRACK AFTER 8 PM"],
    stopIds: ["9529","9527","9525","9523","9521","9519","9517","9515","9513","9511","9509","9507","9505","9503","9501","9499","9497","9495","9493","9491","9489","9487"],
  },
  {
    routeId: "31009",
    shapeId: "211270",
    directionId: 1,
    trips: 7,
    headsigns: ["GREEN LINE PALMETTO STATION"],
    stopIds: ["9501","9499","9497","9495","9493","9491","9489","9487"],
  },
];
